# Generated by Django 3.2 on 2023-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('wid', models.IntegerField(primary_key=True, serialize=False)),
                ('view', models.IntegerField()),
                ('worker_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('e_mail', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('edu_school', models.CharField(max_length=255)),
                ('edu_level', models.CharField(max_length=255)),
                ('work_year', models.IntegerField()),
                ('statue', models.CharField(max_length=255)),
                ('urls', models.URLField(max_length=255)),
                ('url_format', models.CharField(max_length=255)),
                ('hash_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'worker',
                'ordering': ['wid'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['wid'], name='worker_wid_20c430_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['worker_name'], name='worker_worker__60a34a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('hash_code',)},
        ),
    ]
