# Generated by Django 3.2 on 2023-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='wid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
