# Generated by Django 3.2 on 2023-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0002_auto_20230606_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['wid']},
        ),
        migrations.RemoveIndex(
            model_name='worker',
            name='worker_uid_c64213_idx',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='uid',
            new_name='wid',
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['wid'], name='worker_wid_20c430_idx'),
        ),
    ]
