# Generated by Django 3.2 on 2023-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0003_auto_20230606_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Have',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('wid', models.IntegerField()),
            ],
            options={
                'db_table': 'have',
                'ordering': ['hid'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('jname', models.CharField(max_length=255, null=True)),
                ('jneed', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'job',
                'ordering': ['jid'],
            },
        ),
        migrations.CreateModel(
            name='Matchwork',
            fields=[
                ('minfo', models.AutoField(primary_key=True, serialize=False)),
                ('wid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('match', models.FloatField()),
            ],
            options={
                'db_table': 'matchwork',
                'ordering': ['minfo'],
            },
        ),
        migrations.AddIndex(
            model_name='matchwork',
            index=models.Index(fields=['minfo'], name='matchwork_minfo_f384d1_idx'),
        ),
        migrations.AddIndex(
            model_name='matchwork',
            index=models.Index(fields=['wid'], name='matchwork_wid_1120cb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['jid'], name='job_jid_5abccb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['jname'], name='job_jname_b2fd94_idx'),
        ),
        migrations.AddIndex(
            model_name='have',
            index=models.Index(fields=['hid'], name='have_hid_92aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='have',
            index=models.Index(fields=['uid'], name='have_uid_41684d_idx'),
        ),
    ]
