# Generated by Django 3.2 on 2023-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0003_alter_worker_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='e_mail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='edu_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='edu_school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hash_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sex',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='statue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='url_format',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='urls',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
