# Generated by Django 3.2 on 2023-05-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0004_auto_20230527_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='work_year',
            field=models.IntegerField(null=True),
        ),
    ]
