# Generated by Django 3.2 on 2023-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0004_auto_20230606_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jneed',
        ),
        migrations.AddField(
            model_name='job',
            name='jneed_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jneed_edu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jneed_other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='jneed_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
