# Generated by Django 3.2 on 2023-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0005_alter_worker_work_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('hash_code', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['uid'],
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='view',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uid'], name='user_uid_8f8462_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hash_code'], name='user_hash_co_1ccebb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('hash_code',)},
        ),
    ]
