# Generated by Django 3.2 on 2023-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserCenter', '0006_auto_20230611_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fileid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
